# Generated by Django 5.0.1 on 2024-04-19 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='grand_totol',
            new_name='grand_total',
        ),
    ]
