# Generated by Django 5.0.1 on 2024-05-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_payment_payment_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
