# Generated by Django 5.0.1 on 2024-04-01 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additional_product_image',
            old_name='product_varient',
            new_name='product_variant',
        ),
    ]
