# Generated by Django 5.0.1 on 2024-05-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_coupon_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_variant',
            name='offer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='offer_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
