# Generated by Django 5.0.1 on 2024-05-14 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_wishlist_wishlistitem'),
        ('product_management', '0003_coupon_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_management.usercoupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_applied',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='product_management.coupon'),
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon_discount',
            field=models.IntegerField(default=0),
        ),
    ]
