# Generated by Django 5.0.1 on 2024-05-14 16:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cart_coupon_cart_coupon_applied_cart_coupon_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_after_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
